import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const compiled=await build({entryPoints:[root+'lib/use-card-timing.ts'],bundle:true,write:false,platform:'node',format:'iife',globalName:'Timing',plugins:[{name:'hooks',setup(b){b.onResolve({filter:/^react$/},()=>({path:'react',namespace:'fake'}));b.onLoad({filter:/.*/,namespace:'fake'},()=>({contents:'export const useRef=globalThis.ref,useState=globalThis.state,useEffect=globalThis.effect,useMemo=globalThis.memo;',loader:'js'}));}}]});
function harness(modernCrypto=true){
  const disk=new Map(),win=new EventTarget(),doc=new EventTarget(),intervals=new Set();doc.visibilityState='visible';let mono=0,wall=Date.parse('2026-10-08T10:00:00Z'),seq=0,index=0,dirty=false;
  const slots=[],effects=[];let props=['825',{id:'a',front:'问题',back:'答案'},'new',true,false,''];let instance;
  class ClockDate extends Date{constructor(...args){super(...(args.length?args:[wall]));}static now(){return wall;}}
  const ref=value=>{const i=index++;return slots[i] ||= {current:value};};
  const state=initial=>{const i=index++;if(!slots[i])slots[i]={value:typeof initial==='function'?initial():initial};return [slots[i].value,v=>{slots[i].value=typeof v==='function'?v(slots[i].value):v;dirty=true;}];};
  const effect=(fn,deps)=>{const i=index++;const old=slots[i];if(!old || deps.some((v,j)=>v!==old.deps[j]))effects.push(()=>{old?.cleanup?.();slots[i]={deps,fn,cleanup:fn()};});};
  const memo=(fn,deps)=>{const i=index++,old=slots[i];if(!old || deps.some((v,j)=>v!==old.deps[j]))slots[i]={deps,value:fn()};return slots[i].value;};
  const storage={getItem:k=>disk.get(k)??null,setItem:(k,v)=>disk.set(k,v)};
  const context=vm.createContext({localStorage:storage,window:Object.assign(win,{setInterval:fn=>{intervals.add(fn);return fn;},clearInterval:fn=>intervals.delete(fn)}),document:doc,performance:{now:()=>mono},Date:ClockDate,crypto:modernCrypto?{randomUUID:()=>`visit-${++seq}`}:{},CustomEvent:class extends Event{constructor(t,o){super(t);this.detail=o?.detail;}},ref,state,effect,memo,console});
  vm.runInContext(compiled.outputFiles[0].text,context);
  const render=(patch={})=>{Object.entries(patch).forEach(([i,v])=>props[Number(i)]=v);do{dirty=false;index=0;instance=context.Timing.useCardTiming(...props);for(const run of effects.splice(0))run();}while(dirty);return instance;};render();
  const rows=()=>Object.values(JSON.parse(disk.get('yantu-card-timing-v1-825')||'{}'));
  return {disk,rows,render,win,doc,get instance(){return instance;},advance(ms){mono+=ms;wall+=ms;},checkpoint(){for(const fn of intervals)fn();render();},hide(){doc.visibilityState='hidden';doc.dispatchEvent(new Event('visibilitychange'));},show(){doc.visibilityState='visible';doc.dispatchEvent(new Event('visibilitychange'));},unmount(){for(const slot of slots)slot?.cleanup?.();},strictProbe(){for(const slot of slots)if(slot?.fn){slot.cleanup?.();slot.cleanup=slot.fn();}},switchOff(){disk.set('yantu-card-timing-settings-v1','{"enabled":false}');const event=new Event('storage');event.key='yantu-card-timing-settings-v1';win.dispatchEvent(event);render();}};
}
test('StrictMode probe creates no phantom attempt, no duplicated timer',()=>{const h=harness();h.strictProbe();h.advance(8000);h.unmount();assert.equal(h.rows().length,1);assert.equal(h.rows()[0].elapsedMs,8000);});
test('browse/no-ready/no-card never records, entering review starts from zero',()=>{const h=harness();h.render({3:false});h.advance(30000);h.checkpoint();assert.equal(h.rows().length,0);h.render({3:true});h.advance(6000);h.unmount();assert.equal(h.rows()[0].elapsedMs,6000);});
test('rerenders and answer flips do not restart timer; next card gets own duration',()=>{const h=harness();h.advance(6000);h.render();h.advance(4000);h.instance.complete('good');h.render({1:{id:'b',front:'第二题',back:'第二答案'}});h.advance(5000);h.unmount();assert.deepEqual(h.rows().map(r=>[r.cardId,r.elapsedMs,r.status]),[['a',10000,'completed'],['b',5000,'interrupted']]);});
test('background and mobile lock excluded, resume stays same attempt',()=>{const h=harness();h.advance(7000);h.hide();h.advance(600000);h.checkpoint();h.show();h.advance(3000);h.instance.complete('easy');assert.equal(h.rows().length,1);assert.equal(h.rows()[0].elapsedMs,10000);});
test('editor pauses without splitting completed attempt',()=>{const h=harness();h.advance(7000);h.render({4:true});h.advance(90000);h.render({4:false});h.advance(3000);h.instance.complete('good');assert.equal(h.rows().length,1);assert.equal(h.rows()[0].elapsedMs,10000);});
test('disabling through synchronized setting stops foreground timer, enabling starts new visit',()=>{const h=harness();h.advance(7000);h.switchOff();h.advance(30000);h.checkpoint();assert.equal(h.rows().length,1);assert.equal(h.rows()[0].elapsedMs,7000);h.unmount();});
test('account change flushes old account before switch, later cleanup never writes old card to new account',()=>{const h=harness();h.advance(7000);h.win.dispatchEvent(new Event('yantu-account-changing'));assert.equal(h.rows()[0].elapsedMs,7000);h.disk.delete('yantu-card-timing-v1-825');h.disk.set('yantu-sync-active-partition','B');h.advance(20000);h.unmount();assert.equal(h.rows().length,0);});
test('undo retains actual duration and changes only own completed visit',()=>{const h=harness();h.advance(7000);h.instance.complete('good');h.render({1:{id:'b',front:'第二题',back:'第二答案'}});h.advance(3000);h.instance.undo('a');assert.equal(h.rows()[0].status,'undone');assert.equal(h.rows()[0].elapsedMs,7000);h.unmount();assert.equal(h.rows().length,2);});
test('pagehide persists and pageshow resumes, same content changed elsewhere starts separate comparison',()=>{const h=harness();h.advance(7000);h.win.dispatchEvent(new Event('pagehide'));h.advance(50000);h.win.dispatchEvent(new Event('pageshow'));h.advance(3000);h.render({1:{id:'a',front:'问题',back:'更长的新答案'}});h.advance(4000);h.unmount();assert.deepEqual(h.rows().map(r=>r.elapsedMs),[10000,4000]);assert.notEqual(h.rows()[0].contentKey,h.rows()[1].contentKey);});
test('rating same card while timing is disabled cannot undo an older timed attempt',()=>{const h=harness();h.advance(7000);h.instance.complete('again');h.switchOff();h.instance.complete('good');h.instance.undo('a');assert.equal(h.rows()[0].status,'completed');h.unmount();});
test('older Android crypto implementation still produces distinct timed visits',()=>{const h=harness(false);h.advance(5000);h.instance.complete('again');h.render({1:{id:'b',front:'第二题',back:'答案'}});h.advance(4000);h.unmount();assert.equal(h.rows().length,2);assert.notEqual(h.rows()[0].id,h.rows()[1].id);});
test('pagehide stays paused across checkpoints even before visibility becomes hidden',()=>{const h=harness();h.advance(7000);h.win.dispatchEvent(new Event('pagehide'));h.advance(60000);h.checkpoint();h.render({4:true});h.render({4:false});h.advance(60000);h.checkpoint();h.win.dispatchEvent(new Event('pageshow'));h.advance(3000);h.instance.complete('good');assert.equal(h.rows()[0].elapsedMs,10000);h.unmount();});
test('failed account switch restarts timing in the unchanged original account',()=>{const h=harness();h.advance(7000);h.win.dispatchEvent(new Event('yantu-account-changing'));h.advance(20000);h.win.dispatchEvent(new Event('yantu-account-change-failed'));h.render();h.advance(3000);h.instance.complete('good');assert.equal(h.rows().length,2);assert.deepEqual(h.rows().map(r=>r.elapsedMs),[7000,3000]);h.unmount();});
test('remote card edit while page is away cannot restart the foreground clock',()=>{const h=harness();h.advance(7000);h.win.dispatchEvent(new Event('pagehide'));h.render({1:{id:'a',front:'问题',back:'云端修改后的答案'}});h.advance(90000);h.checkpoint();h.win.dispatchEvent(new Event('pageshow'));h.advance(3000);h.instance.complete('good');assert.deepEqual(h.rows().map(r=>r.elapsedMs),[7000,3000]);h.unmount();});
