import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Brain, CalendarDays, Check, ChevronRight, CircleHelp, Clock3, KeyRound, Layers3, Menu, Mic, Send, Settings2, Sparkles, Target, X } from "lucide-react";
import { books, cards, questions, type Question } from "@/lib/study-data";
import { outlines } from "@/lib/outlines";
import { askDeepSeek } from "@/lib/deepseek-browser";

type View = "overview" | "chapters" | "cards" | "quiz" | "feynman" | "planner";
type Review = { due: string; interval: number; ease: number; reps: number };
const subjects = [{ id: "english", name: "英语二", mark: "EN" }, { id: "politics", name: "政治", mark: "PO" }, { id: "333", name: "333 教育综合", mark: "33" }, { id: "825", name: "825 英语专业基础", mark: "82" }];
const localDate = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const today = () => localDate(new Date());
const nav: { id: View; label: string; Icon: typeof BookOpen }[] = [{ id: "overview", label: "今日概览", Icon: Target }, { id: "chapters", label: "章节学习", Icon: BookOpen }, { id: "cards", label: "Anki 闪卡", Icon: Layers3 }, { id: "quiz", label: "真题练习", Icon: CircleHelp }, { id: "feynman", label: "费曼复述", Icon: Mic }, { id: "planner", label: "AI 学习计划", Icon: Sparkles }];

export default function Home() {
  const [subject, setSubject] = useState("333"), [view, setView] = useState<View>("overview");
  const [book, setBook] = useState<string>("principles"), [chapter, setChapter] = useState(1);
  const [flipped, setFlipped] = useState(false), [cardIndex, setCardIndex] = useState(0), [quizIndex, setQuizIndex] = useState(0);
  const [choice, setChoice] = useState<number | null>(null), [score, setScore] = useState({ right: 0, total: 0 });
  const [generated, setGenerated] = useState<Question | null>(null), [quizError, setQuizError] = useState("");
  const [reviews, setReviews] = useState<Record<string, Review>>({}), [done, setDone] = useState<Record<string, boolean>>({});
  const [answer, setAnswer] = useState(""), [feedback, setFeedback] = useState(""), [prompt, setPrompt] = useState("请根据今天的进度，列出今天的学习计划。333 优先复习我选中的章节，并安排闪卡、真题与费曼复述。"), [reply, setReply] = useState("");
  const [key, setKey] = useState(""), [keyOpen, setKeyOpen] = useState(false), [loading, setLoading] = useState(false), [recording, setRecording] = useState(false), [speechError, setSpeechError] = useState(""), [menuOpen, setMenuOpen] = useState(false);
  const recognition = useRef<Speech | null>(null);
  const activeBook = books.find(x => x.id === book) || books[0], chapterName = activeBook.chapters[chapter - 1];
  const chapterCards = cards.filter(x => x.book === book && x.chapter === chapter), visibleCards = chapterCards.length ? chapterCards : cards.filter(x => x.book === book);
  const card = visibleCards[cardIndex % visibleCards.length];
  const chapterQuestions = questions.filter(x => x.book === book && x.chapter === chapter), pool = chapterQuestions.length ? chapterQuestions : questions.filter(x => x.book === book), quiz = generated || pool[quizIndex % pool.length];
  const due = cards.filter(x => !reviews[x.id] || reviews[x.id].due <= today()).length, completed = Object.values(done).filter(Boolean).length;
  const dateLabel = useMemo(() => new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "long" }).format(new Date()), []);
  useEffect(() => { try { setReviews(JSON.parse(localStorage.getItem("yantu-reviews") || "{}")); setDone(JSON.parse(localStorage.getItem("yantu-done") || "{}")); setKey(sessionStorage.getItem("yantu-key") || ""); } catch {} }, []);
  useEffect(() => { localStorage.setItem("yantu-reviews", JSON.stringify(reviews)); }, [reviews]);
  useEffect(() => { localStorage.setItem("yantu-done", JSON.stringify(done)); }, [done]);
  function chooseChapter(b: string, c: number, v: View = "chapters") { setBook(b); setChapter(c); setView(v); setCardIndex(0); setQuizIndex(0); setChoice(null); setGenerated(null); setFlipped(false); }
  function rate(kind: "again" | "hard" | "good" | "easy") {
    if (!card) return;
    const old = reviews[card.id] || { due: today(), interval: 0, ease: 2.5, reps: 0 };
    const days = kind === "again" ? 0 : kind === "hard" ? Math.max(1, Math.round(old.interval * 1.2)) : kind === "good" ? Math.max(1, old.reps ? Math.round(old.interval * old.ease) : 1) : Math.max(3, Math.round(Math.max(old.interval, 1) * old.ease * 1.3));
    const date = new Date(); date.setDate(date.getDate() + days);
    setReviews({ ...reviews, [card.id]: { due: localDate(date), interval: days, ease: Math.max(1.3, old.ease + (kind === "again" ? -0.2 : kind === "easy" ? 0.12 : 0)), reps: kind === "again" ? 0 : old.reps + 1 } });
    setFlipped(false); setCardIndex((cardIndex + 1) % visibleCards.length);
  }
  async function ask(mode: "plan" | "feedback") {
    if (!key.trim()) { setKeyOpen(true); return; }
    const input = mode === "plan" ? prompt : answer;
    if (!input.trim()) return;
    setLoading(true); mode === "plan" ? setReply("") : setFeedback("");
    try {
      const data = await askDeepSeek(key, mode, input, { subject, bookId: book, chapterNo: chapter, book: activeBook.name, chapter: chapterName, done: completed, due, date: today(), exam: "2027年12月初试" });
      mode === "plan" ? setReply(data.text || "") : setFeedback(data.text || "");
    } catch (e) { const message = e instanceof Error ? e.message : "连接失败"; mode === "plan" ? setReply(message) : setFeedback(message); }
    finally { setLoading(false); }
  }
  async function generateQuiz() {
    if (!key.trim()) { setKeyOpen(true); return; }
    setQuizError(""); setLoading(true);
    try {
      const data = await askDeepSeek(key, "quiz", "请出一道与当前章节对应的四选一模拟题。", { bookId: book, chapterNo: chapter, book: activeBook.name, chapter: chapterName, date: today() });
      if (!data.question) throw new Error("生成题目为空，请重试。");
      setGenerated(data.question); setChoice(null);
    } catch (e) { setQuizError(e instanceof Error ? e.message : "生成失败"); }
    finally { setLoading(false); }
  }
  function speech() {
    setSpeechError("");
    if (recording && recognition.current) { recognition.current.stop(); setRecording(false); return; }
    const browser = window as unknown as { SpeechRecognition?: new () => Speech; webkitSpeechRecognition?: new () => Speech };
    const Ctor = browser.SpeechRecognition || browser.webkitSpeechRecognition;
    if (!Ctor) { setSpeechError("当前浏览器不支持语音识别，请在下方打字复述。"); return; }
    const rec = new Ctor(); rec.lang = "zh-CN"; rec.continuous = true; rec.interimResults = false;
    rec.onresult = e => setAnswer(old => old + Array.from(e.results).slice(e.resultIndex).map(x => x[0].transcript).join(""));
    rec.onerror = () => { setRecording(false); setSpeechError("语音识别中断。请检查麦克风权限。"); };
    rec.onend = () => setRecording(false);
    recognition.current = rec; rec.start(); setRecording(true);
  }
  const picker = <div className="pickers"><label>书目<select value={book} onChange={e => chooseChapter(e.target.value, 1, view)}>{books.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>章节<select value={chapter} onChange={e => chooseChapter(book, Number(e.target.value), view)}>{activeBook.chapters.map((x, i) => <option key={x} value={i + 1}>第 {i + 1} 章 · {x}</option>)}</select></label></div>;
  const heading = (label: string, title: string, description: string) => <div className="page-head"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{description}</p></div>;
  return <div className="shell">
    <aside className={"sidebar " + (menuOpen ? "open" : "")}>
      <div className="brand"><span className="brand-logo"><Layers3 size={21}/></span><div><b>研途</b><small>学科英语备考台</small></div><button className="mobile-close" onClick={() => setMenuOpen(false)}><X size={20}/></button></div>
      <div className="side-caption">考试科目</div><nav className="side-nav">{subjects.map(x => <button key={x.id} className={subject === x.id ? "selected" : ""} onClick={() => { setSubject(x.id); setView("overview"); setMenuOpen(false); }}><span className="subject-mark">{x.mark}</span>{x.name}{x.id === "333" && <small>已接入</small>}</button>)}</nav>
      <div className="side-line"/><div className="side-caption">学习工具</div><nav className="side-nav tools">{nav.map(({ id, label, Icon }) => <button key={id} className={view === id ? "selected" : ""} onClick={() => { setView(id); setMenuOpen(false); }}><Icon size={18}/>{label}</button>)}</nav>
      <div className="side-bottom"><div className="target-date"><CalendarDays size={18}/><span><b>2027 年 12 月</b><small>目标初试</small></span></div><button className="key-link" onClick={() => setKeyOpen(true)}><KeyRound size={17}/> DeepSeek 密钥 <small>{key ? "已配置" : "未配置"}</small></button></div>
    </aside>
    {menuOpen && <div className="menu-shade" onClick={() => setMenuOpen(false)}/>}
    <main className="main"><header className="topbar"><button className="mobile-menu" onClick={() => setMenuOpen(true)}><Menu size={22}/></button><span>研途 <ChevronRight size={15}/> {subjects.find(x => x.id === subject)?.name} <ChevronRight size={15}/> <b>{nav.find(x => x.id === view)?.label}</b></span><div><span className="date-chip"><CalendarDays size={15}/>{dateLabel}</span><button className="icon-button" onClick={() => setKeyOpen(true)} aria-label="设置密钥"><Settings2 size={18}/></button></div></header>
      <div className="content">{subject !== "333" ? <div className="subject-empty"><BookOpen size={34}/><span className="eyebrow">{subjects.find(x => x.id === subject)?.name}</span><h1>这一科的资料区已预留</h1><p>当前先把 333 的四本《应试解析》做成学习流程。加入这门科目的资料后，章节、练习和进度会出现在这里。</p><button className="primary" onClick={() => setSubject("333")}>先学习 333</button></div> : <>
        {view === "overview" && <>{heading("GOOD TO SEE YOU", "今天，继续向目标靠近。", "从一个章节开始，学一点、讲出来、再用真题检验。")}<div className="stats"><Stat Icon={BookOpen} label="333 已学章节" value={completed + " / 42"} note="四本应试解析"/><Stat Icon={Layers3} label="待复习闪卡" value={String(due)} note="按间隔复习安排"/><Stat Icon={Target} label="练习正确率" value={score.total ? Math.round(score.right / score.total * 100) + "%" : "—"} note={score.total ? "本次已答 " + score.total + " 题" : "开始真题练习"}/></div><div className="dashboard"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">FOUR BOOKS</span><h2>333 · 四本书</h2></div><button className="text-button" onClick={() => setView("chapters")}>查看全部 <ChevronRight size={16}/></button></div><div className="book-list">{books.map(x => { const count = Object.keys(done).filter(k => k.startsWith(x.id + "-") && done[k]).length; return <button key={x.id} className="book-row" onClick={() => chooseChapter(x.id, 1)}><span className="book-cover" style={{ background: x.tone }}>{x.short}</span><span><b>{x.name}</b><small>{x.chapters.length} 章 · {count} 章已学</small></span><div className="mini-progress"><i style={{ width: 100 * count / x.chapters.length + "%", background: x.tone }}/></div><ChevronRight size={17}/></button>; })}</div></section><section className="panel next-panel"><span className="eyebrow">YOUR NEXT STEP</span><h2>继续上次的节奏</h2><div className="next-chapter"><span>{String(chapter).padStart(2, "0")}</span><div><small>{activeBook.name} · 第 {chapter} 章</small><b>{chapterName}</b></div></div><div className="next-actions"><button className="primary" onClick={() => setView("cards")}>开始闪卡复习</button><button className="secondary" onClick={() => setView("quiz")}>做一道真题</button></div><small className="source-status"><Check size={15}/> 题目附有年份、题号与来源页码</small></section></div><section className="panel source-panel"><div><span className="eyebrow">SOURCE LIBRARY</span><h2>资料与真题</h2><p>四本《27KC 333 应试解析》建立章节目录；练习题来自工作区 2024、2025、2026 年 333 真题。扫描页经 OCR 校对后使用。</p></div><div className="year-chips"><span>2024 真题</span><span>2025 真题</span><span>2026 真题</span></div></section></>}
        {view === "chapters" && <>{heading("BOOK BY BOOK", "从章节开始，形成自己的知识地图", "选书、选章；完成学习后标记进度，并进入闪卡或真题。")}<div className="book-tabs">{books.map(x => <button key={x.id} className={book === x.id ? "active" : ""} onClick={() => chooseChapter(x.id, 1)}><i style={{ background: x.tone }}/>{x.name}</button>)}</div><div className="chapter-layout"><section className="panel chapter-list"><span className="eyebrow">{activeBook.chapters.length} CHAPTERS</span><h2>{activeBook.name}</h2>{activeBook.chapters.map((x, i) => <button key={x} className={"chapter-row " + (chapter === i + 1 ? "active" : "")} onClick={() => chooseChapter(book, i + 1)}><span>{String(i + 1).padStart(2, "0")}</span><b>{x}</b>{done[book + "-" + (i + 1)] ? <Check size={17}/> : <ChevronRight size={17}/>}</button>)}</section><section className="panel chapter-detail"><span className="eyebrow">{activeBook.name} / 第 {chapter} 章</span><h2>{chapterName}</h2><p>先浏览教材，再用闪卡主动回忆，最后用真题检验；复述反馈会结合当前章节。</p><div className="detail-count"><div><b>{chapterCards.length}</b><small>已校对闪卡</small></div><div><b>{chapterQuestions.length}</b><small>匹配真题</small></div></div>{(outlines[book]?.[chapter - 1] || []).length > 0 && <div className="section-outline"><strong>本章目录</strong>{outlines[book][chapter - 1].map((name, index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span>{name}</div>)}</div>}{!chapterCards.length && <p className="notice">该章尚无人工核对闪卡。可先阅读原书，再进行费曼复述。</p>}<div className="detail-buttons"><button className="primary" onClick={() => setView("cards")}>背诵闪卡</button><button className="secondary" onClick={() => setView("feynman")}>口述本章</button></div><button className="mark-done" onClick={() => setDone({ ...done, [book + "-" + chapter]: !done[book + "-" + chapter] })}><Check size={16}/>{done[book + "-" + chapter] ? "已完成 · 点击撤销" : "标记本章已学习"}</button></section></div></>}
        {view === "cards" && <>{heading("ACTIVE RECALL", "Anki 闪卡复习", "先自己回答，再翻面核对；按掌握程度决定下次复习时间。")}{picker}<div className="study-meta"><Clock3 size={16}/> 今日待复习 {due} 张</div>{card ? <div className="flash-area"><div className="flash-top"><span>{activeBook.name} · 第 {chapter} 章</span><span>{cardIndex % visibleCards.length + 1} / {visibleCards.length}</span></div><button className="flash-card" onClick={() => setFlipped(!flipped)}><small>{flipped ? "答案" : "问题"}</small><strong>{flipped ? card.back : card.front}</strong><span>{flipped ? card.source : "点击卡片查看答案"}</span></button><div className="rate-actions">{flipped ? <><button onClick={() => rate("again")}>重来<small>今天</small></button><button onClick={() => rate("hard")}>困难<small>短间隔</small></button><button onClick={() => rate("good")}>记住了<small>正常</small></button><button onClick={() => rate("easy")}>很熟悉<small>长间隔</small></button></> : <button className="primary" onClick={() => setFlipped(true)}>显示答案</button>}</div></div> : <div className="panel empty">本书还没有已校对闪卡。换一本书，或先做费曼复述。</div>}</>}
        {view === "quiz" && <>{heading("PAST PAPERS", "333 真题练习", "答完立即查看正确答案、解析与出处。")}{picker}<div className="study-meta">{chapterQuestions.length ? "当前章节匹配题" : "当前章暂无已映射题 · 展示同书真题"} <button className="generate-button" disabled={loading} onClick={generateQuiz}><Sparkles size={15}/>{loading ? "出题中…" : "AI 出本章模拟题"}</button></div>{quizError && <p className="error">{quizError}</p>}<section className="panel quiz-card"><div className="quiz-top"><span>{generated ? "AI 模拟题" : quiz.year + " 真题"}</span><small>{generated ? "当前章节" : "第 " + (quizIndex % pool.length + 1) + " / " + pool.length + " 题"}</small></div><h2>{quiz.stem}</h2><div className="options">{quiz.options.map((x, i) => <button key={i} disabled={choice !== null} className={choice === null ? "" : i === quiz.answer ? "correct" : choice === i ? "wrong" : ""} onClick={() => { setChoice(i); setScore({ right: score.right + Number(i === quiz.answer), total: score.total + 1 }); }}><span>{"ABCD"[i]}</span>{x}</button>)}</div>{choice !== null && <div className="explanation"><b>{choice === quiz.answer ? "答对了" : "正确答案：" + "ABCD"[quiz.answer]}</b><p>{quiz.explanation}</p><small>来源：{quiz.source}</small></div>}<div className="quiz-footer"><span>{score.total ? "本次 " + score.right + " / " + score.total + " 题正确" : "先选一个答案"}</span><button className="primary" onClick={() => { setGenerated(null); setQuizIndex(quizIndex + 1); setChoice(null); }}>下一题</button></div></section></>}
        {view === "feynman" && <>{heading("TEACH IT BACK", "把知识讲给“别人”听", "像讲课一样解释一个概念。语音转文字或直接打字，DeepSeek 会给评分与反馈。")}{picker}<div className="feynman-layout"><section className="panel speaking"><span className="eyebrow">CURRENT TOPIC</span><h2>{chapterName}</h2><p>建议按“是什么 → 为什么 → 举一个课堂例子 → 易混点”讲述。尽量不用照着教材念。</p><button className="secondary" onClick={speech}><Mic size={19}/>{recording ? "停止语音输入" : "开始语音输入"}</button>{speechError && <p className="error">{speechError}</p>}<small>语音识别由浏览器提供，请允许麦克风权限。文字可以随时修改。</small></section><section className="panel writing"><label htmlFor="answer">我的复述</label><textarea id="answer" value={answer} onChange={e => setAnswer(e.target.value)} placeholder="例如：我会这样向同学解释这个概念……"/><div className="write-footer"><small>{answer.length} 字</small><button className="primary" disabled={!answer.trim() || loading} onClick={() => ask("feedback")}><Sparkles size={17}/>{loading ? "分析中…" : "让 DeepSeek 评分"}</button></div>{feedback && <div className="ai-result"><b><Brain size={18}/> DeepSeek 反馈</b><p>{feedback}</p></div>}</section></div></>}
        {view === "planner" && <>{heading("AI STUDY COACH", "为今天定一个可执行的计划", "输入你的时间、状态和想学的章节；DeepSeek 会结合 2027 年 12 月初试目标安排。")}<div className="planner-layout"><section className="panel planner"><div className="planner-title"><span><Sparkles size={21}/></span><div><h2>今天想怎么学？</h2><p>可以直接修改下面的问题，再发送给 DeepSeek。</p></div></div><textarea value={prompt} onChange={e => setPrompt(e.target.value)} aria-label="学习计划要求"/><div className="write-footer"><small>当前章节：{activeBook.name} · 第 {chapter} 章</small><button className="primary" disabled={loading || !prompt.trim()} onClick={() => ask("plan")}><Send size={17}/>{loading ? "生成中…" : "生成学习计划"}</button></div>{reply && <div className="ai-result"><b><Sparkles size={18}/> 今日计划</b><p>{reply}</p></div>}</section><section className="panel context"><span className="eyebrow">CONTEXT</span><h2>计划会参考</h2><p><BookOpen size={18}/>当前章节 <b>{chapterName}</b></p><p><Layers3 size={18}/>待复习闪卡 <b>{due} 张</b></p><p><Target size={18}/>目标初试 <b>2027 年 12 月</b></p><div className="tip">告诉 AI “今天只有 2 小时”“想重点背教心”，计划会更贴合你。</div></section></div></>}
      </>}</div>
    </main>
    {keyOpen && <div className="modal-backdrop" onClick={() => setKeyOpen(false)}><div className="key-modal" role="dialog" aria-modal="true" aria-labelledby="key-title" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setKeyOpen(false)}><X size={20}/></button><span className="key-icon"><KeyRound size={23}/></span><h2 id="key-title">连接 DeepSeek</h2><p>填入你自己的 API Key，即可生成计划并获得复述评分。密钥只保存在当前浏览器会话，请求由浏览器直接发送给 DeepSeek。</p><label htmlFor="api-key">API Key</label><input id="api-key" type="password" value={key} onChange={e => setKey(e.target.value)} placeholder="sk-..." autoComplete="off"/><div className="modal-actions"><button className="secondary" onClick={() => { setKey(""); sessionStorage.removeItem("yantu-key"); setKeyOpen(false); }}>清除</button><button className="primary" onClick={() => { sessionStorage.setItem("yantu-key", key.trim()); setKeyOpen(false); }}>保存并继续</button></div></div></div>}
  </div>;
}
type Speech = { lang: string; continuous: boolean; interimResults: boolean; onresult: (e: { results: ArrayLike<ArrayLike<{ transcript: string }>>; resultIndex: number }) => void; onerror: () => void; onend: () => void; start: () => void; stop: () => void };
function Stat({ Icon, label, value, note }: { Icon: typeof BookOpen; label: string; value: string; note: string }) { return <div className="stat"><span className="stat-icon"><Icon size={20}/></span><small>{label}</small><strong>{value}</strong><span>{note}</span></div>; }
